//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioMVC8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atencion
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Sintoma { get; set; }
        public string Diagnostico { get; set; }
        public string Medicamentos { get; set; }
        public int DoctorId { get; set; }
        public int PacienteId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
