//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioMVC8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EjercicioMVC8BDContainer : DbContext
    {
        public EjercicioMVC8BDContainer()
            : base("name=EjercicioMVC8BDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Unidad> Unidades { get; set; }
        public virtual DbSet<Planta> Plantas { get; set; }
        public virtual DbSet<Doctor> Doctores { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<Atencion> Atenciones { get; set; }
        public virtual DbSet<Estadia> Estadias { get; set; }
    }
}
