//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioMVC8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadia
    {
        public int Id { get; set; }
        public System.DateTime Entrada { get; set; }
        public System.DateTime Salida { get; set; }
        public Nullable<System.DateTime> Cita { get; set; }
        public int PacienteId { get; set; }
        public int UnidadId { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Unidad Unidad { get; set; }
    }
}
